---
title: "COVID-19 Mobility Model Building"
author: "Sumedh Shah"
subtitle: 'w203 Lab 2'
output:
  pdf_document: default
  word_document: default
---




```{r load packages, message=FALSE}
library(gridExtra)                       
library(tidyverse)
library(magrittr)
library(ggplot2)
library(patchwork)
library(sandwich)
library(lmtest)
library(stargazer)
theme_set(theme_minimal())
knitr::opts_chunk$set(dpi = 300)
```

```{r load data}
covid_mobility_data = read.csv('../data/processed/processed_data.csv')
head(covid_mobility_data)
```


```{r mobility histograms}

retail_rec_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = avg_retail_rec_change) +
  geom_histogram(bins=30) +
  labs(title = 'Distribution of Retail/Rec Mobility Change') +
  xlab('Percent Change in Retail/Rec Mobility') +
  ylab('Count') 

park_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = avg_parks_change) +
  geom_histogram(bins=30) +
  labs(title = 'Distribution of Park Mobility Change') +
  xlab('Percent Change in Park Mobility') +
  ylab('Count') 

#Plot above mobility histograms
retail_rec_hist/park_hist


```

```{r at home and mask order histogram}
#At Home Order histogram
at_home_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = at_home_order) +
  geom_histogram(bins=30) +
  labs(title = 'Distribution of At Home Order') +
  xlab('At Home Order') +
  ylab('Count') 

# Mask Order Histogram
mask_order_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = mask_order) +
  geom_histogram(bins=30) +
  labs(title = 'Distribution of Mask Order') +
  xlab('Mask Order') +
  ylab('Count') 


#Plot above histograms
at_home_hist/mask_order_hist

```

```{r new cases histogram}

new_cases_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = new_cases_per_100k) +
  geom_histogram(bins=30) +
  xlim(-100,2000) +
  labs(title = 'Distribution of New COVID-19 Cases Per 100K') +
  xlab('New COVID-19 Cases') +
  ylab('Count') 

log_new_cases_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = log(new_cases_per_100k)) +
  geom_histogram(bins=30) +
  labs(title = 'Log Distribution of New COVID-19 Cases Per 100K') +
  xlab('Log(New COVID-19 Cases)') +
  ylab('Count') 



#Plot above new cases histograms
new_cases_hist/log_new_cases_hist
```

```{r quarantine length histograms}

quarantine_length_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = quarantine_length) +
  geom_histogram(bins=30) +
  xlim(-10,100) +
  labs(title = 'Distribution of Quarantine Length') +
  xlab('Quarantine Length (Number of Days)') +
  ylab('Count')

log_quarantine_length_hist <- covid_mobility_data %>%
  ggplot() +
  theme(plot.title = element_text(hjust = 0.5)) +
  aes(x = log(quarantine_length)) +
  geom_histogram(bins=30) +
  labs(title = 'Log Distribution of Quarantine Length') +
  xlab('Log(Quarantine Length)') +
  ylab('Count')

# Plot quarantine length histograms
quarantine_length_hist/log_quarantine_length_hist
```

```{r scatter plots}
#Analyze each independent variable compared to the dependent variable (avg_rec_retail_change)

quarantine_length_avg_change <- covid_mobility_data %>%
  ggplot() +
  aes(x = quarantine_length, y = avg_retail_rec_change) +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("Quarantine Length vs Average Retail_Rec Change ") +
  xlab("Quarantine Length (Days)") +
  ylab("Average Retail_Rec Change (%)") 

at_home_avg_change <- covid_mobility_data %>%
  ggplot() +
  aes(x = at_home_order, y = avg_retail_rec_change) +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("At Home Order vs Average Retail_Rec Change ") +
  xlab("At Home Order") +
  ylab("Average Retail_Rec Change (%)") 


mask_order_avg_change <- covid_mobility_data %>%
  ggplot() +
  aes(x = mask_order, y = avg_retail_rec_change) +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("Mask Order vs Average Retail_Rec Change ") +
  xlab("Mask Order") +
  ylab("Average Retail_Rec Change (%)") 


new_cases_avg_change <- covid_mobility_data %>%
  ggplot() +
  aes(x = new_cases_per_100k, y = avg_retail_rec_change) +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("New Cases Per 100K vs Average Retail_Rec Change ") +
  xlab("New Cases Per 100K") +
  ylab("Average Retail_Rec Change (%)") 

pop_density_avg_change <- covid_mobility_data %>%
  ggplot() +
  aes(x = population_density, y = avg_retail_rec_change) +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  ggtitle("Population Density vs Average Retail_Rec Change ") +
  xlab("Population Density") +
  ylab("Average Retail_Rec Change (%)") 

#Plot above scatterplots
quarantine_length_avg_change
at_home_avg_change
mask_order_avg_change
new_cases_avg_change
pop_density_avg_change
```



# Produce Descriptive Models

```{r fit linear model, echo=TRUE, warning=FALSE, message=FALSE}
# Create LM models 
model_1 <- lm(avg_retail_rec_change ~ at_home_order, data=covid_mobility_data)
model_2 <- lm(avg_retail_rec_change ~ 
             at_home_order +                          # Primary variable of interest
             quarantine_length + mask_order +         # Other covid policies/happenings that may confound
             population_density + new_cases_per_100k, # State level effects that may confound
              data=covid_mobility_data)
model_3 <- lm(avg_retail_rec_change ~ 
               at_home_order +                           # Primary variable of interest
               quarantine_length + mask_order +          # Other covid policies/happenings that may confound
               population_density + new_cases_per_100k + # State level effects that may confound
               new_cases + population +                  # Likely collinear variables
               avg_parks_change,                         # mobility related control we decided against, data=covid_mobility_data)
                data=covid_mobility_data)



```




### Interpret the model coefficients
```{r, echo=TRUE, warning=FALSE, message=FALSE}

# View details of both models
stargazer( 
  model_1,
  model_2,
  model_3,
  se =list(sqrt(diag(vcovHC(model_1))),sqrt(diag(vcovHC(model_2)))),
  type = 'text'
)

```





